<?php

namespace App\Repositories;

use App\Http\Requests\ProductRequest;
use App\Models\Product;

class ProductRepository {

    protected $product;

    public function __construct(Product $product)
    {
        $this->product = $product;
    }

    public function create(ProductRequest $request)
    {
        $product = new Product(); 
        $product->name = $request['nazwa'];
        $product->code_qr = $request['kod'];
        $product->category_id = $request['kategoria'];

        $pdf = $request->file('pdf');
        $path = $pdf->store('public/pdf');
        $filename_pdf = $pdf->hashName();

        $image = $request['zdjęcie'];
        $path2 = $image->store('public/images');
        $filename_image = $image->hashName();

        // original file name: $name2 = $image->getClientOriginalName();
        // name generated by laravel: $name2 = $image->hashName();
        // path to file: $path2

        $product->pdf_name = $filename_pdf;
        $product->image_name = $filename_image;
        $product->user_id = $request->user()->id;

        $product->save();

        return $product;
    }

}